sonar.projectKey=AppContosoUnivID
sonar.working.directory=C:\\01S\\03_c_ex\\35-SonarQube\\04-SampleProject\\ContosoUniversity\\.sonarqube\\out\\.sonar
sonar.projectBaseDir=C:\\01S\\03_c_ex\\35-SonarQube\\04-SampleProject\\ContosoUniversity
sonar.pullrequest.cache.basepath=C:\\01S\\03_c_ex\\35-SonarQube\\04-SampleProject\\ContosoUniversity
sonar.sources=\
"C:\\01S\\03_c_ex\\35-SonarQube\\04-SampleProject\\ContosoUniversity\\.vs\\config\\applicationhost.config",\
"C:\\01S\\03_c_ex\\35-SonarQube\\04-SampleProject\\ContosoUniversity\\.vs\\ContosoUniversity\\config\\applicationhost.config",\
"C:\\01S\\03_c_ex\\35-SonarQube\\04-SampleProject\\ContosoUniversity\\.vs\\ContosoUniversity\\v17\\DocumentLayout.backup.json",\
"C:\\01S\\03_c_ex\\35-SonarQube\\04-SampleProject\\ContosoUniversity\\.vs\\ContosoUniversity\\v17\\DocumentLayout.json",\
"C:\\01S\\03_c_ex\\35-SonarQube\\04-SampleProject\\ContosoUniversity\\packages\\bootstrap.3.0.0\\Content\\Content\\bootstrap-theme.css",\
"C:\\01S\\03_c_ex\\35-SonarQube\\04-SampleProject\\ContosoUniversity\\packages\\bootstrap.3.0.0\\Content\\Content\\bootstrap-theme.min.css",\
"C:\\01S\\03_c_ex\\35-SonarQube\\04-SampleProject\\ContosoUniversity\\packages\\bootstrap.3.0.0\\Content\\Content\\bootstrap.css",\
"C:\\01S\\03_c_ex\\35-SonarQube\\04-SampleProject\\ContosoUniversity\\packages\\bootstrap.3.0.0\\Content\\Content\\bootstrap.min.css",\
"C:\\01S\\03_c_ex\\35-SonarQube\\04-SampleProject\\ContosoUniversity\\packages\\bootstrap.3.0.0\\Content\\Scripts\\bootstrap.js",\
"C:\\01S\\03_c_ex\\35-SonarQube\\04-SampleProject\\ContosoUniversity\\packages\\bootstrap.3.0.0\\Content\\Scripts\\bootstrap.min.js",\
"C:\\01S\\03_c_ex\\35-SonarQube\\04-SampleProject\\ContosoUniversity\\packages\\EntityFramework.6.1.1\\tools\\init.ps1",\
"C:\\01S\\03_c_ex\\35-SonarQube\\04-SampleProject\\ContosoUniversity\\packages\\EntityFramework.6.1.1\\tools\\install.ps1",\
"C:\\01S\\03_c_ex\\35-SonarQube\\04-SampleProject\\ContosoUniversity\\packages\\jQuery.1.10.2\\Tools\\common.ps1",\
"C:\\01S\\03_c_ex\\35-SonarQube\\04-SampleProject\\ContosoUniversity\\packages\\jQuery.1.10.2\\Tools\\install.ps1",\
"C:\\01S\\03_c_ex\\35-SonarQube\\04-SampleProject\\ContosoUniversity\\packages\\jQuery.1.10.2\\Tools\\jquery-1.10.2.intellisense.js",\
"C:\\01S\\03_c_ex\\35-SonarQube\\04-SampleProject\\ContosoUniversity\\packages\\jQuery.1.10.2\\Tools\\uninstall.ps1",\
"C:\\01S\\03_c_ex\\35-SonarQube\\04-SampleProject\\ContosoUniversity\\packages\\jQuery.1.10.2\\Content\\Scripts\\jquery-1.10.2-vsdoc.js",\
"C:\\01S\\03_c_ex\\35-SonarQube\\04-SampleProject\\ContosoUniversity\\packages\\jQuery.1.10.2\\Content\\Scripts\\jquery-1.10.2.js",\
"C:\\01S\\03_c_ex\\35-SonarQube\\04-SampleProject\\ContosoUniversity\\packages\\jQuery.1.10.2\\Content\\Scripts\\jquery-1.10.2.min.js",\
"C:\\01S\\03_c_ex\\35-SonarQube\\04-SampleProject\\ContosoUniversity\\packages\\jQuery.Validation.1.11.1\\Content\\Scripts\\jquery.validate-vsdoc.js",\
"C:\\01S\\03_c_ex\\35-SonarQube\\04-SampleProject\\ContosoUniversity\\packages\\jQuery.Validation.1.11.1\\Content\\Scripts\\jquery.validate.js",\
"C:\\01S\\03_c_ex\\35-SonarQube\\04-SampleProject\\ContosoUniversity\\packages\\jQuery.Validation.1.11.1\\Content\\Scripts\\jquery.validate.min.js",\
"C:\\01S\\03_c_ex\\35-SonarQube\\04-SampleProject\\ContosoUniversity\\packages\\Microsoft.jQuery.Unobtrusive.Validation.3.2.0\\Content\\Scripts\\jquery.validate.unobtrusive.js",\
"C:\\01S\\03_c_ex\\35-SonarQube\\04-SampleProject\\ContosoUniversity\\packages\\Microsoft.jQuery.Unobtrusive.Validation.3.2.0\\Content\\Scripts\\jquery.validate.unobtrusive.min.js",\
"C:\\01S\\03_c_ex\\35-SonarQube\\04-SampleProject\\ContosoUniversity\\packages\\Modernizr.2.6.2\\Tools\\common.ps1",\
"C:\\01S\\03_c_ex\\35-SonarQube\\04-SampleProject\\ContosoUniversity\\packages\\Modernizr.2.6.2\\Tools\\install.ps1",\
"C:\\01S\\03_c_ex\\35-SonarQube\\04-SampleProject\\ContosoUniversity\\packages\\Modernizr.2.6.2\\Tools\\uninstall.ps1",\
"C:\\01S\\03_c_ex\\35-SonarQube\\04-SampleProject\\ContosoUniversity\\packages\\Modernizr.2.6.2\\Content\\Scripts\\modernizr-2.6.2.js",\
"C:\\01S\\03_c_ex\\35-SonarQube\\04-SampleProject\\ContosoUniversity\\packages\\Newtonsoft.Json.6.0.3\\tools\\install.ps1",\
"C:\\01S\\03_c_ex\\35-SonarQube\\04-SampleProject\\ContosoUniversity\\packages\\PagedList.Mvc.4.5.0.0\\Content\\Content\\PagedList.css",\
"C:\\01S\\03_c_ex\\35-SonarQube\\04-SampleProject\\ContosoUniversity\\packages\\Respond.1.2.0\\content\\Scripts\\respond.js",\
"C:\\01S\\03_c_ex\\35-SonarQube\\04-SampleProject\\ContosoUniversity\\packages\\Respond.1.2.0\\content\\Scripts\\respond.min.js",\
"C:\\01S\\03_c_ex\\35-SonarQube\\04-SampleProject\\ContosoUniversity\\packages\\WebGrease.1.5.2\\tools\\install.ps1",\
"C:\\01S\\03_c_ex\\35-SonarQube\\04-SampleProject\\ContosoUniversity\\packages\\WebGrease.1.5.2\\tools\\uninstall.ps1"

264E21D6-4024-4A53-B1BE-1CD42F3348FE.sonar.projectKey=AppContosoUnivID:264E21D6-4024-4A53-B1BE-1CD42F3348FE
264E21D6-4024-4A53-B1BE-1CD42F3348FE.sonar.projectName=ContosoUniversity
264E21D6-4024-4A53-B1BE-1CD42F3348FE.sonar.projectBaseDir=C:\\01S\\03_c_ex\\35-SonarQube\\04-SampleProject\\ContosoUniversity\\ContosoUniversity
264E21D6-4024-4A53-B1BE-1CD42F3348FE.sonar.sourceEncoding=utf-8
264E21D6-4024-4A53-B1BE-1CD42F3348FE.sonar.tests=
264E21D6-4024-4A53-B1BE-1CD42F3348FE.sonar.sources=\
"C:\\01S\\03_c_ex\\35-SonarQube\\04-SampleProject\\ContosoUniversity\\ContosoUniversity\\App_Start\\BundleConfig.cs",\
"C:\\01S\\03_c_ex\\35-SonarQube\\04-SampleProject\\ContosoUniversity\\ContosoUniversity\\App_Start\\FilterConfig.cs",\
"C:\\01S\\03_c_ex\\35-SonarQube\\04-SampleProject\\ContosoUniversity\\ContosoUniversity\\App_Start\\RouteConfig.cs",\
"C:\\01S\\03_c_ex\\35-SonarQube\\04-SampleProject\\ContosoUniversity\\ContosoUniversity\\Controllers\\CourseController.cs",\
"C:\\01S\\03_c_ex\\35-SonarQube\\04-SampleProject\\ContosoUniversity\\ContosoUniversity\\Controllers\\DepartmentController.cs",\
"C:\\01S\\03_c_ex\\35-SonarQube\\04-SampleProject\\ContosoUniversity\\ContosoUniversity\\Controllers\\HomeController.cs",\
"C:\\01S\\03_c_ex\\35-SonarQube\\04-SampleProject\\ContosoUniversity\\ContosoUniversity\\Controllers\\InstructorController.cs",\
"C:\\01S\\03_c_ex\\35-SonarQube\\04-SampleProject\\ContosoUniversity\\ContosoUniversity\\Controllers\\StudentController.cs",\
"C:\\01S\\03_c_ex\\35-SonarQube\\04-SampleProject\\ContosoUniversity\\ContosoUniversity\\DAL\\SchoolConfiguration.cs",\
"C:\\01S\\03_c_ex\\35-SonarQube\\04-SampleProject\\ContosoUniversity\\ContosoUniversity\\DAL\\SchoolContext.cs",\
"C:\\01S\\03_c_ex\\35-SonarQube\\04-SampleProject\\ContosoUniversity\\ContosoUniversity\\DAL\\SchoolInitializer.cs",\
"C:\\01S\\03_c_ex\\35-SonarQube\\04-SampleProject\\ContosoUniversity\\ContosoUniversity\\DAL\\SchoolInterceptorLogging.cs",\
"C:\\01S\\03_c_ex\\35-SonarQube\\04-SampleProject\\ContosoUniversity\\ContosoUniversity\\DAL\\SchoolInterceptorTransientErrors.cs",\
"C:\\01S\\03_c_ex\\35-SonarQube\\04-SampleProject\\ContosoUniversity\\ContosoUniversity\\Global.asax.cs",\
"C:\\01S\\03_c_ex\\35-SonarQube\\04-SampleProject\\ContosoUniversity\\ContosoUniversity\\Logging\\ILogger.cs",\
"C:\\01S\\03_c_ex\\35-SonarQube\\04-SampleProject\\ContosoUniversity\\ContosoUniversity\\Logging\\Logger.cs",\
"C:\\01S\\03_c_ex\\35-SonarQube\\04-SampleProject\\ContosoUniversity\\ContosoUniversity\\Migrations\\201411021828194_InitialCreate.cs",\
"C:\\01S\\03_c_ex\\35-SonarQube\\04-SampleProject\\ContosoUniversity\\ContosoUniversity\\Migrations\\201411021828194_InitialCreate.Designer.cs",\
"C:\\01S\\03_c_ex\\35-SonarQube\\04-SampleProject\\ContosoUniversity\\ContosoUniversity\\Migrations\\201411021834484_MaxLengthOnNames.cs",\
"C:\\01S\\03_c_ex\\35-SonarQube\\04-SampleProject\\ContosoUniversity\\ContosoUniversity\\Migrations\\201411021834484_MaxLengthOnNames.Designer.cs",\
"C:\\01S\\03_c_ex\\35-SonarQube\\04-SampleProject\\ContosoUniversity\\ContosoUniversity\\Migrations\\201411021841373_ComplexDataModel.cs",\
"C:\\01S\\03_c_ex\\35-SonarQube\\04-SampleProject\\ContosoUniversity\\ContosoUniversity\\Migrations\\201411021841373_ComplexDataModel.Designer.cs",\
"C:\\01S\\03_c_ex\\35-SonarQube\\04-SampleProject\\ContosoUniversity\\ContosoUniversity\\Migrations\\201411021957458_DepartmentSP.cs",\
"C:\\01S\\03_c_ex\\35-SonarQube\\04-SampleProject\\ContosoUniversity\\ContosoUniversity\\Migrations\\201411021957458_DepartmentSP.Designer.cs",\
"C:\\01S\\03_c_ex\\35-SonarQube\\04-SampleProject\\ContosoUniversity\\ContosoUniversity\\Migrations\\201411022009135_RowVersion.cs",\
"C:\\01S\\03_c_ex\\35-SonarQube\\04-SampleProject\\ContosoUniversity\\ContosoUniversity\\Migrations\\201411022009135_RowVersion.Designer.cs",\
"C:\\01S\\03_c_ex\\35-SonarQube\\04-SampleProject\\ContosoUniversity\\ContosoUniversity\\Migrations\\201411022351064_Inheritance.cs",\
"C:\\01S\\03_c_ex\\35-SonarQube\\04-SampleProject\\ContosoUniversity\\ContosoUniversity\\Migrations\\201411022351064_Inheritance.Designer.cs",\
"C:\\01S\\03_c_ex\\35-SonarQube\\04-SampleProject\\ContosoUniversity\\ContosoUniversity\\Migrations\\Configuration.cs",\
"C:\\01S\\03_c_ex\\35-SonarQube\\04-SampleProject\\ContosoUniversity\\ContosoUniversity\\Models\\Course.cs",\
"C:\\01S\\03_c_ex\\35-SonarQube\\04-SampleProject\\ContosoUniversity\\ContosoUniversity\\Models\\Department.cs",\
"C:\\01S\\03_c_ex\\35-SonarQube\\04-SampleProject\\ContosoUniversity\\ContosoUniversity\\Models\\Enrollment.cs",\
"C:\\01S\\03_c_ex\\35-SonarQube\\04-SampleProject\\ContosoUniversity\\ContosoUniversity\\Models\\Instructor.cs",\
"C:\\01S\\03_c_ex\\35-SonarQube\\04-SampleProject\\ContosoUniversity\\ContosoUniversity\\Models\\OfficeAssignment.cs",\
"C:\\01S\\03_c_ex\\35-SonarQube\\04-SampleProject\\ContosoUniversity\\ContosoUniversity\\Models\\Person.cs",\
"C:\\01S\\03_c_ex\\35-SonarQube\\04-SampleProject\\ContosoUniversity\\ContosoUniversity\\Models\\Student.cs",\
"C:\\01S\\03_c_ex\\35-SonarQube\\04-SampleProject\\ContosoUniversity\\ContosoUniversity\\Properties\\AssemblyInfo.cs",\
"C:\\01S\\03_c_ex\\35-SonarQube\\04-SampleProject\\ContosoUniversity\\ContosoUniversity\\ViewModels\\AssignedCourseData.cs",\
"C:\\01S\\03_c_ex\\35-SonarQube\\04-SampleProject\\ContosoUniversity\\ContosoUniversity\\ViewModels\\EnrollmentDateGroup.cs",\
"C:\\01S\\03_c_ex\\35-SonarQube\\04-SampleProject\\ContosoUniversity\\ContosoUniversity\\ViewModels\\InstructorIndexData.cs",\
"C:\\01S\\03_c_ex\\35-SonarQube\\04-SampleProject\\ContosoUniversity\\ContosoUniversity\\Content\\bootstrap.css",\
"C:\\01S\\03_c_ex\\35-SonarQube\\04-SampleProject\\ContosoUniversity\\ContosoUniversity\\Content\\bootstrap.min.css",\
"C:\\01S\\03_c_ex\\35-SonarQube\\04-SampleProject\\ContosoUniversity\\ContosoUniversity\\Content\\PagedList.css",\
"C:\\01S\\03_c_ex\\35-SonarQube\\04-SampleProject\\ContosoUniversity\\ContosoUniversity\\favicon.ico",\
"C:\\01S\\03_c_ex\\35-SonarQube\\04-SampleProject\\ContosoUniversity\\ContosoUniversity\\fonts\\glyphicons-halflings-regular.svg",\
"C:\\01S\\03_c_ex\\35-SonarQube\\04-SampleProject\\ContosoUniversity\\ContosoUniversity\\Global.asax",\
"C:\\01S\\03_c_ex\\35-SonarQube\\04-SampleProject\\ContosoUniversity\\ContosoUniversity\\Content\\Site.css",\
"C:\\01S\\03_c_ex\\35-SonarQube\\04-SampleProject\\ContosoUniversity\\ContosoUniversity\\Scripts\\bootstrap.js",\
"C:\\01S\\03_c_ex\\35-SonarQube\\04-SampleProject\\ContosoUniversity\\ContosoUniversity\\Scripts\\bootstrap.min.js",\
"C:\\01S\\03_c_ex\\35-SonarQube\\04-SampleProject\\ContosoUniversity\\ContosoUniversity\\Scripts\\jquery-1.10.2.js",\
"C:\\01S\\03_c_ex\\35-SonarQube\\04-SampleProject\\ContosoUniversity\\ContosoUniversity\\Scripts\\jquery-1.10.2.min.js",\
"C:\\01S\\03_c_ex\\35-SonarQube\\04-SampleProject\\ContosoUniversity\\ContosoUniversity\\Scripts\\jquery.validate.js",\
"C:\\01S\\03_c_ex\\35-SonarQube\\04-SampleProject\\ContosoUniversity\\ContosoUniversity\\Scripts\\jquery.validate.min.js",\
"C:\\01S\\03_c_ex\\35-SonarQube\\04-SampleProject\\ContosoUniversity\\ContosoUniversity\\Scripts\\jquery.validate.unobtrusive.js",\
"C:\\01S\\03_c_ex\\35-SonarQube\\04-SampleProject\\ContosoUniversity\\ContosoUniversity\\Scripts\\jquery.validate.unobtrusive.min.js",\
"C:\\01S\\03_c_ex\\35-SonarQube\\04-SampleProject\\ContosoUniversity\\ContosoUniversity\\Scripts\\modernizr-2.6.2.js",\
"C:\\01S\\03_c_ex\\35-SonarQube\\04-SampleProject\\ContosoUniversity\\ContosoUniversity\\Scripts\\respond.js",\
"C:\\01S\\03_c_ex\\35-SonarQube\\04-SampleProject\\ContosoUniversity\\ContosoUniversity\\Scripts\\respond.min.js",\
"C:\\01S\\03_c_ex\\35-SonarQube\\04-SampleProject\\ContosoUniversity\\ContosoUniversity\\Scripts\\_references.js",\
"C:\\01S\\03_c_ex\\35-SonarQube\\04-SampleProject\\ContosoUniversity\\ContosoUniversity\\Web.config",\
"C:\\01S\\03_c_ex\\35-SonarQube\\04-SampleProject\\ContosoUniversity\\ContosoUniversity\\Web.Debug.config",\
"C:\\01S\\03_c_ex\\35-SonarQube\\04-SampleProject\\ContosoUniversity\\ContosoUniversity\\Web.Release.config",\
"C:\\01S\\03_c_ex\\35-SonarQube\\04-SampleProject\\ContosoUniversity\\ContosoUniversity\\Views\\Web.config",\
"C:\\01S\\03_c_ex\\35-SonarQube\\04-SampleProject\\ContosoUniversity\\ContosoUniversity\\Views\\_ViewStart.cshtml",\
"C:\\01S\\03_c_ex\\35-SonarQube\\04-SampleProject\\ContosoUniversity\\ContosoUniversity\\Views\\Shared\\Error.cshtml",\
"C:\\01S\\03_c_ex\\35-SonarQube\\04-SampleProject\\ContosoUniversity\\ContosoUniversity\\Views\\Shared\\_Layout.cshtml",\
"C:\\01S\\03_c_ex\\35-SonarQube\\04-SampleProject\\ContosoUniversity\\ContosoUniversity\\Views\\Home\\About.cshtml",\
"C:\\01S\\03_c_ex\\35-SonarQube\\04-SampleProject\\ContosoUniversity\\ContosoUniversity\\Views\\Home\\Contact.cshtml",\
"C:\\01S\\03_c_ex\\35-SonarQube\\04-SampleProject\\ContosoUniversity\\ContosoUniversity\\Views\\Home\\Index.cshtml",\
"C:\\01S\\03_c_ex\\35-SonarQube\\04-SampleProject\\ContosoUniversity\\ContosoUniversity\\Scripts\\jquery-1.10.2.min.map",\
"C:\\01S\\03_c_ex\\35-SonarQube\\04-SampleProject\\ContosoUniversity\\ContosoUniversity\\Views\\Student\\Create.cshtml",\
"C:\\01S\\03_c_ex\\35-SonarQube\\04-SampleProject\\ContosoUniversity\\ContosoUniversity\\Views\\Student\\Delete.cshtml",\
"C:\\01S\\03_c_ex\\35-SonarQube\\04-SampleProject\\ContosoUniversity\\ContosoUniversity\\Views\\Student\\Details.cshtml",\
"C:\\01S\\03_c_ex\\35-SonarQube\\04-SampleProject\\ContosoUniversity\\ContosoUniversity\\Views\\Student\\Edit.cshtml",\
"C:\\01S\\03_c_ex\\35-SonarQube\\04-SampleProject\\ContosoUniversity\\ContosoUniversity\\Views\\Student\\Index.cshtml",\
"C:\\01S\\03_c_ex\\35-SonarQube\\04-SampleProject\\ContosoUniversity\\ContosoUniversity\\Views\\Course\\Create.cshtml",\
"C:\\01S\\03_c_ex\\35-SonarQube\\04-SampleProject\\ContosoUniversity\\ContosoUniversity\\Views\\Course\\Delete.cshtml",\
"C:\\01S\\03_c_ex\\35-SonarQube\\04-SampleProject\\ContosoUniversity\\ContosoUniversity\\Views\\Course\\Details.cshtml",\
"C:\\01S\\03_c_ex\\35-SonarQube\\04-SampleProject\\ContosoUniversity\\ContosoUniversity\\Views\\Course\\Edit.cshtml",\
"C:\\01S\\03_c_ex\\35-SonarQube\\04-SampleProject\\ContosoUniversity\\ContosoUniversity\\Views\\Course\\Index.cshtml",\
"C:\\01S\\03_c_ex\\35-SonarQube\\04-SampleProject\\ContosoUniversity\\ContosoUniversity\\Views\\Instructor\\Create.cshtml",\
"C:\\01S\\03_c_ex\\35-SonarQube\\04-SampleProject\\ContosoUniversity\\ContosoUniversity\\Views\\Instructor\\Delete.cshtml",\
"C:\\01S\\03_c_ex\\35-SonarQube\\04-SampleProject\\ContosoUniversity\\ContosoUniversity\\Views\\Instructor\\Details.cshtml",\
"C:\\01S\\03_c_ex\\35-SonarQube\\04-SampleProject\\ContosoUniversity\\ContosoUniversity\\Views\\Instructor\\Edit.cshtml",\
"C:\\01S\\03_c_ex\\35-SonarQube\\04-SampleProject\\ContosoUniversity\\ContosoUniversity\\Views\\Instructor\\Index.cshtml",\
"C:\\01S\\03_c_ex\\35-SonarQube\\04-SampleProject\\ContosoUniversity\\ContosoUniversity\\Views\\Department\\Create.cshtml",\
"C:\\01S\\03_c_ex\\35-SonarQube\\04-SampleProject\\ContosoUniversity\\ContosoUniversity\\Views\\Department\\Delete.cshtml",\
"C:\\01S\\03_c_ex\\35-SonarQube\\04-SampleProject\\ContosoUniversity\\ContosoUniversity\\Views\\Department\\Details.cshtml",\
"C:\\01S\\03_c_ex\\35-SonarQube\\04-SampleProject\\ContosoUniversity\\ContosoUniversity\\Views\\Department\\Edit.cshtml",\
"C:\\01S\\03_c_ex\\35-SonarQube\\04-SampleProject\\ContosoUniversity\\ContosoUniversity\\Views\\Department\\Index.cshtml",\
"C:\\01S\\03_c_ex\\35-SonarQube\\04-SampleProject\\ContosoUniversity\\ContosoUniversity\\Views\\Course\\UpdateCourseCredits.cshtml",\
"C:\\01S\\03_c_ex\\35-SonarQube\\04-SampleProject\\ContosoUniversity\\ContosoUniversity\\fonts\\glyphicons-halflings-regular.woff",\
"C:\\01S\\03_c_ex\\35-SonarQube\\04-SampleProject\\ContosoUniversity\\ContosoUniversity\\fonts\\glyphicons-halflings-regular.ttf",\
"C:\\01S\\03_c_ex\\35-SonarQube\\04-SampleProject\\ContosoUniversity\\ContosoUniversity\\fonts\\glyphicons-halflings-regular.eot",\
"C:\\01S\\03_c_ex\\35-SonarQube\\04-SampleProject\\ContosoUniversity\\ContosoUniversity\\packages.config",\
"C:\\01S\\03_c_ex\\35-SonarQube\\04-SampleProject\\ContosoUniversity\\ContosoUniversity\\Migrations\\201411021828194_InitialCreate.resx",\
"C:\\01S\\03_c_ex\\35-SonarQube\\04-SampleProject\\ContosoUniversity\\ContosoUniversity\\Migrations\\201411021834484_MaxLengthOnNames.resx",\
"C:\\01S\\03_c_ex\\35-SonarQube\\04-SampleProject\\ContosoUniversity\\ContosoUniversity\\Migrations\\201411021841373_ComplexDataModel.resx",\
"C:\\01S\\03_c_ex\\35-SonarQube\\04-SampleProject\\ContosoUniversity\\ContosoUniversity\\Migrations\\201411021957458_DepartmentSP.resx",\
"C:\\01S\\03_c_ex\\35-SonarQube\\04-SampleProject\\ContosoUniversity\\ContosoUniversity\\Migrations\\201411022009135_RowVersion.resx",\
"C:\\01S\\03_c_ex\\35-SonarQube\\04-SampleProject\\ContosoUniversity\\ContosoUniversity\\Migrations\\201411022351064_Inheritance.resx",\
"C:\\01S\\03_c_ex\\35-SonarQube\\04-SampleProject\\ContosoUniversity\\ContosoUniversity\\Scripts\\jquery-1.10.2.intellisense.js",\
"C:\\01S\\03_c_ex\\35-SonarQube\\04-SampleProject\\ContosoUniversity\\ContosoUniversity\\Scripts\\jquery.validate-vsdoc.js",\
"C:\\01S\\03_c_ex\\35-SonarQube\\04-SampleProject\\ContosoUniversity\\ContosoUniversity\\Project_Readme.html",\
"C:\\01S\\03_c_ex\\35-SonarQube\\04-SampleProject\\ContosoUniversity\\ContosoUniversity\\.vs\\ContosoUniversity.csproj.dtbcache.json",\
"C:\\01S\\03_c_ex\\35-SonarQube\\04-SampleProject\\ContosoUniversity\\ContosoUniversity\\bin\\ContosoUniversity.dll.config"

264E21D6-4024-4A53-B1BE-1CD42F3348FE.sonar.cs.analyzer.projectOutPaths=\
"C:\\01S\\03_c_ex\\35-SonarQube\\04-SampleProject\\ContosoUniversity\\.sonarqube\\out\\0"
264E21D6-4024-4A53-B1BE-1CD42F3348FE.sonar.cs.roslyn.reportFilePaths=\
"C:\\01S\\03_c_ex\\35-SonarQube\\04-SampleProject\\ContosoUniversity\\.sonarqube\\out\\0\\Issues.json"

264E21D6-4024-4A53-B1BE-1CD42F3348FE.sonar.working.directory=C:\\01S\\03_c_ex\\35-SonarQube\\04-SampleProject\\ContosoUniversity\\.sonarqube\\out\\.sonar\\mod0
sonar.host.url=http://localhost:9000
sonar.visualstudio.enable=false

sonar.modules=264E21D6-4024-4A53-B1BE-1CD42F3348FE

